# See Serverless configuration docs:
# https://github.com/serverless/serverless-azure-functions/blob/master/docs/CONFIG.md

service: githubhooks

frameworkVersion: '2'

provider:
  name: azure
  region: West Europe
  runtime: python3.8

  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions
package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!venv/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'
    - '!chevah/github_hooks_server/tests/**'
    - '!*.pyc'

functions:
  ping:
    handler: chevah/github_hooks_server/server.ping
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous
  hook:
    handler: chevah/github_hooks_server/server.hook
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
